name: Reveal Secret LINK (hati-hati!)

on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret dengan trik (spasi antar karakter)
        run: |
          echo "Nilai secret LINK (dengan spasi):"
          echo "${{ secrets.LINK }}" | sed 's/./& /g'
